<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-QRGQV12" name="org.my.samplelogin.example_login.org.my.samplelogin.example_login.NegativeTests" tests="4" failures="1" timestamp="02 Aug 2018 22:29:48 GMT" time="3.191" errors="0">
  <testcase name="testLoginWithPasswordNoUsername" time="0.356" classname="org.my.samplelogin.example_login.org.my.samplelogin.example_login.NegativeTests"/>
  <testcase name="testLoginWithUsernameNoPassword" time="0.381" classname="org.my.samplelogin.example_login.org.my.samplelogin.example_login.NegativeTests"/>
  <testcase name="testSimpleLoginBadCredentials" time="0.814" classname="org.my.samplelogin.example_login.org.my.samplelogin.example_login.NegativeTests">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:49)
at org.my.samplelogin.example_login.org.my.samplelogin.example_login.NegativeTests.testSimpleLoginBadCredentials(NegativeTests.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSimpleLoginBadCredentials -->
  <testcase name="testLoginEmptyCredentials" time="1.640" classname="org.my.samplelogin.example_login.org.my.samplelogin.example_login.NegativeTests"/>
</testsuite> <!-- org.my.samplelogin.example_login.org.my.samplelogin.example_login.NegativeTests -->
